### ISSUE TITLE
请问下如何登陆

### ISSUE THREAD

**Issue by Solmonz** [xingsu1021/pthelper#2]
请问下我找不到相对于的数值，实在哪里添加上去
[{"name": "hdhome", "name_cn": "\u5bb6\u56ed", "index_url": "https://hdhome.org", "torrent_url": "", "bonus_url": "", "sign_type": "general"}]

**Comment by xingsu1021** [comment]
这个在初始化的时候会自动加入的
{'name':'hdfans','name_cn':'红豆饭','index_url':'https://hdfans.org','sign_type':'general'},
                  {'name':'1ptba','name_cn':'壹PT吧','index_url':'https://1ptba.com','sign_type':'general'},
                  {'name':'ptchina','name_cn':'铂金学院','index_url':'https://ptchina.org','sign_type':'general'},
                  {'name':'hdchina','name_cn':'瓷器','index_url':'https://hdchina.org','sign_type':'hdchina'},
                  {'name':'hdmayi','name_cn':'小蚂蚁','index_url':'http://hdmayi.com','sign_type':'general'},
                  {'name':'msg','name_cn':'马杀鸡','index_url':'https://pt.msg.vg','sign_type':'nosign'},
                  {'name':'beitai','name_cn':'备胎','index_url':'https://www.beitai.pt','sign_type':'nosign'},
                  {'name':'oshen','name_cn':'奥申','index_url':'http://www.oshen.win','sign_type':'nosign'},
                  {'name':'avgv','name_cn':'爱薇','index_url':'http://avgv.cc','sign_type':'nosign'},
                  {'name':'eastgame','name_cn':'吐鲁番','index_url':'https://pt.eastgame.org','sign_type':'nosign'},
                  {'name':'keepfrds','name_cn':'朋友','index_url':'https://pt.keepfrds.com','sign_type':'keepfrds'},
                  {'name':'tjupt','name_cn':'北洋园','index_url':'https://tjupt.org','sign_type':'tjupt'},
                  {'name':'itzmx','name_cn':'分享站','index_url':'https://pt.itzmx.com','sign_type':'nosign'},
                  {'name':'greatposterwall','name_cn':'海豹','index_url':'https://greatposterwall.com','sign_type':'greatposterwall'},
                  {'name':'hd','name_cn':'海带','index_url':'https://www.hd.ai','sign_type':'hd'},
                  {'name':'m-team','name_cn':'馒头','index_url':'https://kp.m-team.cc','sign_type':'nosign'},
                  {'name':'lemonhd','name_cn':'柠檬','index_url':'https://lemonhd.org','sign_type':'general'},
                  {'name':'btschool','name_cn':'学校','index_url':'https://pt.btschool.club','sign_type':'btschool'},
                  {'name':'pthome','name_cn':'铂金家','index_url':'https://pthome.net','sign_type':'general'},
                  {'name':'totheglory','name_cn':'听听歌','index_url':'https://totheglory.im','sign_type':'ttg'},
                  {'name':'hdhome','name_cn':'家园','index_url':'https://hdhome.org','sign_type':'general'},
                  {'name':'pterclub','name_cn':'猫站','index_url':'https://pterclub.com','sign_type':'pterclub'},
                  {'name':'ourbits','name_cn':'我堡','index_url':'https://ourbits.club','sign_type':'general'},
                  {'name':'hdsky','name_cn':'天空','index_url':'https://hdsky.me','sign_type':'hdsky'},
                  {'name':'hares','name_cn':'白兔','index_url':'https://club.hares.top','sign_type':'hares'},
                  {'name':'et8','name_cn':'他吹吹风','index_url':'https://et8.org','sign_type':'nosign'},
                  {'name':'audiences','name_cn':'观众','index_url':'https://audiences.me','sign_type':'general'},
                  {'name':'hdcity','name_cn':'城市','index_url':'https://hdcity.city','sign_type':'hdcity'},
                  {'name':'open','name_cn':'皇后','index_url':'https://open.cd','sign_type':'opencd'},
                  {'name':'hdarea','name_cn':'高清视界','index_url':'https://www.hdarea.co','sign_type':'hdarea'},
                  {'name':'soulvoice','name_cn':'聆音','index_url':'https://pt.soulvoice.club','sign_type':'general'},
                  {'name':'nicept','name_cn':'老师','index_url':'https://www.nicept.net','sign_type':'general'},
                  {'name':'haidan','name_cn':'海胆','index_url':'https://www.haidan.video','sign_type':'haidan'},
                  {'name':'3wmg','name_cn':'芒果','index_url':'https://www.3wmg.com','sign_type':'general'},
                  {'name':'discfan','name_cn':'碟粉','index_url':'https://discfan.net','sign_type':'general'},
                  {'name':'htpt','name_cn':'海棠','index_url':'https://www.htpt.cc','sign_type':'general'},
                  {'name':'hddolby','name_cn':'杜比','index_url':'https://www.hddolby.com','sign_type':'general'},
                  {'name':'hdzone','name_cn':'高清地带','index_url':'https://hdzone.me','sign_type':'general'},
                  {'name':'pttime','name_cn':'时间','index_url':'https://www.pttime.org','sign_type':'general'},
                  {'name':'hdatmos','name_cn':'阿童木','index_url':'https://hdatmos.club','sign_type':'general'},
                  {'name':'52pt','name_cn':'52PT','index_url':'https://52pt.site','sign_type':'pt52'},
                  {'name':'hdtime','name_cn':'高清时间','index_url':'https://hdtime.org','sign_type':'general'},
                  {'name':'asf','name_cn':'A-SOUL','index_url':'https://pt.asf.ink','sign_type':'general'},
                  {'name':'ptsbao','name_cn':'烧包','index_url':'https://ptsbao.club','sign_type':'ptsbao'},
                  {'name':'ssd','name_cn':'春天','index_url':'https://springsunday.net','sign_type':'ssd'},
                  {'name':'gainbound','name_cn':'丐帮','index_url':'https://gainbound.net','sign_type':'general'},
                  {'name':'joyhd','name_cn':'开心','index_url':'https://www.joyhd.net','sign_type':'nosign'},
                  {'name':'carpt','name_cn':'车PT','index_url':'https://carpt.net','sign_type':'general'},
                  {'name':'piggo','name_cn':'猪猪网','index_url':'https://piggo.me','sign_type':'general'},

**Comment by Solmonz** [comment]
Ok  请问下这个还会更新吗 比如对接企业微信等

**Comment by xingsu1021** [comment]
目前没需求，如果有功能需要，可以提出进行开发。

**Comment by Solmonz** [comment]
好的，那请问可以提几个小意见嘛，比如：对接企业微信、或者wxplus 这样会更方便

**Comment by xingsu1021** [comment]
可以，你可以确认下需求，我这边做开发就好了

**Comment by Solmonz** [comment]
目前推送这个需求就是这个了，会更方便 辛苦大佬了

**Comment by xingsu1021** [comment]
可以

**Comment by xingsu1021** [comment]
已支持企业微信

**Comment by Solmonz** [comment]
佬，我拉docker版，好像没显示……拉错了嘛

**Comment by Solmonz** [comment]
可以了，大佬。需要删除旧映像，重拉一次就行
我在多问一个小问题：这个可以模版可以签到别的论坛吗，比如 远景、矿渣、吾爱这样

**Comment by xingsu1021** [comment]
不支持，目前只做PT类的

**Comment by Solmonz** [comment]
大佬 请教下 使用 docker-compose 报错
error getting credentials - err: exit status 1, out: `GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files`
需要怎么解决
系统：unbuntu

**Comment by xingsu1021** [comment]
代码里的docker-compose.yml不能用的

**Comment by Solmonz** [comment]
啊 这 我改怎么修改
version: '3.7'
services:
  flexget:
    image: pthelper:v2.0.0
    container_name: pthelper
    restart: always
    volumes:
      - /home/data/docker-compose/pthelper/db:/db
      - /home/data/docker-compose/pthelper/logs:/logs
      - /home/data/docker-compose/pthelper/backups:/backups
    ports:
      - "58000:80"

**Comment by xingsu1021** [comment]
你这个配置可以的，你这个好像是系统问题，docker-compose这个什么版本，ubuntu什么版本

**Comment by xingsu1021** [comment]
apt install gnupg2 pass试试这个

**Comment by Solmonz** [comment]
没搞定，后面装自己家里的nas 上了
对了，老哥，这个推送能优化下吗，企业微信看着好乱（附：如下）


hdhome(家园) 这是您的第 74 次签到，已连续签到 16 天，本次签到获得 70 个魔力值。
beitai(备胎) 魔力: 3,670.4 ,分享率: 无限  ,新消息: 1 (0 新)  
pthome(铂金家) 这是您的第 87 次签到，已连续签到 14 天，本次签到获得 30 个魔力值。
hdatmos(阿童木) 这是您的第 77 次签到，已连续签到 16 天，本次签到获得 85 个魔力值。点击白色背景的圆点进行补签。你目前拥有补签卡 30 张。<span style="float:right">今日签到排名：723 / 723</span>
lemonhd(柠檬) 这是您的第 89 次签到，已连续签到 16 天，本次签到获得 44 魔力值。
魔力:238,213,分享率:无限,新消息:1 (0 新)
totheglory(听听歌) 您已连续签到16天，奖励25积分，明天继续签到将获得26积分奖励。

**Comment by xingsu1021** [comment]
你用的是最新的2.0.0+版本吗？

**Comment by Solmonz** [comment]
是的

**Comment by Solmonz** [comment]
![Uploading 9CDB8B44-BD04-4330-BBE2-D14CE36516C6.jpeg…]()

**Comment by xingsu1021** [comment]
接口数据都是统一的，现在新版不会看到详细的信息，都是优化的。你这边尝试拉下2.0.0或者2.0.1试试。最新的latest是周五上传的

**Comment by yuxingxu** [comment]
我是最新的2.0.1 大佬 
大佬有TG huoz  QQ 嘛

**Comment by xingsu1021** [comment]
https://t.me/sftang
