### ISSUE TITLE
部分站点签到出错

### ISSUE THREAD

**Issue by woniux** [xingsu1021/pthelper#5]
tjupt(北洋园) [签到失败,错误:无法匹配电影名称]
某不可说 [cookie失效]
hdchina(瓷器) [签到失败,错误:不正确的CSRF / Incorrect CSRF token]

**Comment by xingsu1021** [comment]
北洋园图片识别不是百分百，因此最好添加重试任务，任务时间和签到时间间隔至少一分钟，不可分钟重叠
cookie失效，发现个别浏览器获取的cookie有问题，目前edge的cookie准确率达到99%
hdchina调整签到策略，已阻断自动签到，目前未修复

**Comment by woniux** [comment]
感谢解答
